<!DOCTYPE html>
<html lang="en">  <!-- Sets language to English -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
{{-- @import('flowbite'); --}}
@vite(['resources/css/app.css','resources/js/app.js'])
<link rel="stylesheet" href="{{ asset('/assets/admin/css/style.css') }}">

{{-- <script src= "{{ asset('/resources/css/flowbite.min.css') }}"></script>
<script src= "{{ asset('/resources/css/app.css') }}"></script>
<script src= "{{ asset('/resources/css/app.js') }}"></script> --}}

@extends('layouts.navbar')
@section('navbar-content')
@if(auth()->check())
<section>
    <div class="px-4 pt-6 2xl:px-0">
      <title>Dashboard</title>
        <div class="grid gap-4 xl:grid-cols-2 2xl:grid-cols-3">
            <!-- Main widget -->
            <div class="p-4 bg-white border border-gray-200 rounded-lg shadow-sm 2xl:col-span-2 dark:border-gray-700 sm:p-6 dark:bg-gray-800">
              <div class="flex items-center justify-between mb-4">
                <h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white pe-1">
                  @if (Auth::user()->usertype == 'User') Your ticket progress @else Your team's progress @endif
                </h5>
                  <svg data-popover-target="chart-info" data-popover-placement="bottom" class="w-3.5 h-3.5 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white cursor-pointer ms-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm0 16a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3Zm1-5.034V12a1 1 0 0 1-2 0v-1.418a1 1 0 0 1 1.038-.999 1.436 1.436 0 0 0 1.488-1.441 1.501 1.501 0 1 0-3-.116.986.986 0 0 1-1.037.961 1 1 0 0 1-.96-1.037A3.5 3.5 0 1 1 11 11.466Z"/>
                  </svg>
                  <div data-popover id="chart-info" role="tooltip" class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-xs opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400">
                      <div class="p-3 space-y-2">
                          <h3 class="font-semibold text-gray-900 dark:text-white">Activity growth - Incremental</h3>
                          <p>This graph shows the total count for Open, In Progress, On-hold, Closed and Cancelled tickets</p>
                          {{-- <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
                          <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p> --}}
                          <a href="#" class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700 hover:underline">Read more <svg class="w-2 h-2 ms-1.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                    </svg></a>
                      </div>
                      <div data-popper-arrow></div>
                  </div>
              </div>
              
              <div class="bg-gray-50 dark:bg-gray-700 p-3 rounded-lg">
                <div class="grid grid-cols-5 gap-3 mb-2">
                  <dl class="bg-blue-50 dark:bg-gray-600 rounded-lg flex flex-col items-center justify-center h-[78px]">
                    <dt id="open-tickets" class="w-8 h-8 rounded-full bg-blue-100 dark:bg-gray-500 text-blue-600 dark:text-blue-300 text-sm font-medium flex items-center justify-center mb-1" data-count="{{$tickets->where('status','Open')->count()}}">{{$tickets->where('status','Open')->count()}}</dt>
                    <dd class="text-blue-600 dark:text-blue-300 text-sm font-medium">Open</dd>
                  </dl>
                  <dl class="bg-orange-50 dark:bg-gray-600 rounded-lg flex flex-col items-center justify-center h-[78px]">
                    <dt id="inprogress-tickets" class="w-8 h-8 rounded-full bg-orange-100 dark:bg-gray-500 text-orange-600 dark:text-orange-300 text-sm font-medium flex items-center justify-center mb-1" data-count="{{$tickets->where('status','In Progress')->count()}}">{{$tickets->where('status','In Progress')->count()}}</dt>
                    <dd class="text-orange-600 dark:text-orange-300 text-sm font-medium">In Progress</dd>
                  </dl>
                  <dl class="bg-purple-50 dark:bg-gray-600 rounded-lg flex flex-col items-center justify-center h-[78px]">
                    <dt id="onhold-tickets" class="w-8 h-8 rounded-full bg-purple-100 dark:bg-gray-500 text-purple-600 dark:text-purple-300 text-sm font-medium flex items-center justify-center mb-1" data-count="{{$tickets->where('status','On-hold')->count()}}">{{$tickets->where('status','On-hold')->count()}}</dt>
                    <dd class="text-purple-600 dark:text-purple-300 text-sm font-medium">On-hold</dd>
                  </dl>
                  <dl class="bg-teal-50 dark:bg-gray-600 rounded-lg flex flex-col items-center justify-center h-[78px]">
                    <dt id="closed-tickets" class="w-8 h-8 rounded-full bg-teal-100 dark:bg-gray-500 text-teal-600 dark:text-teal-300 text-sm font-medium flex items-center justify-center mb-1" data-count="{{$tickets->where('status','Closed')->count()}}">{{$tickets->where('status','Closed')->count()}}</dt>
                    <dd class="text-teal-600 dark:text-teal-300 text-sm font-medium">Closed</dd>
                  </dl>
                  <dl class="bg-red-50 dark:bg-gray-600 rounded-lg flex flex-col items-center justify-center h-[78px]">
                    <dt id="cancelled-tickets" class="w-8 h-8 rounded-full bg-red-100 dark:bg-gray-500 text-red-600 dark:text-red-300 text-sm font-medium flex items-center justify-center mb-1" data-count="{{$tickets->where('status','Cancelled')->count()}}">{{$tickets->where('status','Cancelled')->count()}}</dt>
                    <dd class="text-red-600 dark:text-red-300 text-sm font-medium">Cancelled</dd>
                  </dl>
                </div>
                <button data-collapse-toggle="more-details" type="button" class="hover:underline text-xs text-gray-500 dark:text-gray-400 font-medium inline-flex items-center">Show more details <svg class="w-2 h-2 ms-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                  </svg>
                </button>
                <div id="more-details" class="border-gray-200 border-t dark:border-gray-600 pt-3 mt-3 space-y-2 hidden">
                  <dl class="flex items-center justify-between">
                    <dt class="text-gray-500 dark:text-gray-400 text-sm font-normal">Average task completion rate:</dt>
                    <dd class="bg-green-100 text-green-800 text-xs font-medium inline-flex items-center px-2.5 py-1 rounded-md dark:bg-green-900 dark:text-green-300">
                      <svg class="w-2.5 h-2.5 me-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13V1m0 0L1 5m4-4 4 4"/>
                      </svg> 57%
                    </dd>
                  </dl>
                  <dl class="flex items-center justify-between">
                    <dt class="text-gray-500 dark:text-gray-400 text-sm font-normal">Days until sprint ends:</dt>
                    <dd class="bg-gray-100 text-gray-800 text-xs font-medium inline-flex items-center px-2.5 py-1 rounded-md dark:bg-gray-600 dark:text-gray-300">13 days</dd>
                  </dl>
                  <dl class="flex items-center justify-between">
                    <dt class="text-gray-500 dark:text-gray-400 text-sm font-normal">Next meeting:</dt>
                    <dd class="bg-gray-100 text-gray-800 text-xs font-medium inline-flex items-center px-2.5 py-1 rounded-md dark:bg-gray-600 dark:text-gray-300">Thursday</dd>
                  </dl>
                </div>
              </div>

              <!-- Radial Chart -->
              <div class="py-6" id="radial-chart"></div>

              <div id="main-chart"></div>
              
              <!-- Card Footer -->
              {{-- <div class="flex items-center justify-between pt-3 mt-4 border-t border-gray-200 sm:pt-6 dark:border-gray-700"> --}}
                {{-- <div>
                  <button id="dropdownButton" class="inline-flex items-center p-2 text-sm font-medium text-center text-gray-500 rounded-lg hover:text-gray-900 dark:text-gray-400 dark:hover:text-white" type="button" data-dropdown-toggle="weekly-sales-dropdown" data-dropdown-trigger="click">Last 7 days
                  <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg>
                  </button>
                  <!-- Dropdown menu -->
                  <div id="weekly-sales-dropdown" class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded shadow dark:bg-gray-700 dark:divide-gray-600">
                      <div class="px-4 py-3" role="none">
                        <p class="text-sm font-medium text-gray-900 truncate dark:text-white" role="none">
                          Sep 16, 2021 - Sep 22, 2021
                        </p>
                      </div>
                      <ul class="py-1" role="none">
                        <li>
                          <a href="#" onclick="updateTickets('yesterday')" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Yesterday</a>
                        </li>
                        <li>
                          <a href="#" onclick="updateTickets('today')" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Today</a>
                        </li>
                        <li>
                          <a href="#" onclick="updateTickets('last7days')" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Last 7 days</a>
                        </li>
                        <li>
                          <a href="#" onclick="updateTickets('last30days')" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Last 30 days</a>
                        </li>
                        <li>
                          <a href="#" onclick="updateTickets('last90days')" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Last 90 days</a>
                        </li>
                      </ul>
                      <div class="py-1" role="none">
                        <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Custom...</a>
                      </div>                      
                  </div>
                </div> --}}
                {{-- <div class="flex-shrink-0">
                  <a href="#" class="inline-flex items-center p-2 text-xs font-medium uppercase rounded-lg text-blue-700 sm:text-sm hover:bg-gray-100 dark:text-blue-500 dark:hover:bg-gray-700">
                    Full Report
                    <svg class="w-4 h-4 ml-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg>
                  </a>
                </div> --}}
              {{-- </div> --}}
            </div>

            <!--Tabs widget -->
            @if (Auth::user()->usertype != 'User')
              <div class="p-4 bg-white border border-gray-200 rounded-lg shadow-sm dark:border-gray-700 sm:p-6 dark:bg-gray-800">
                <h3 class="flex items-center mb-4 text-lg font-semibold text-gray-900 dark:text-white">User statistics
                <button data-popover-target="popover-description" data-popover-placement="bottom-end" type="button"><svg class="w-4 h-4 ml-2 text-gray-400 hover:text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg><span class="sr-only">Show information</span></button>
                </h3>
                <div data-popover id="popover-description" role="tooltip" class="absolute z-10 invisible inline-block text-sm font-light text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400">
                  <div class="p-3 space-y-2">
                      <h3 class="font-semibold text-gray-900 dark:text-white">Current session</h3>
                      <p>List of active sessions.</p>
                      <h3 class="font-semibold text-gray-900 dark:text-white">Recently added</h3>
                      <p>List of recently created users.</p>
                      <a href="#" class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700">Read more <svg class="w-4 h-4 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg></a>
                  </div>
                  <div data-popper-arrow></div>
                </div>
                <div class="sm:hidden">
                    <label for="tabs" class="sr-only">Select tab</label>
                    <select id="tabs" class="bg-gray-50 border-0 border-b border-gray-200 text-gray-900 text-sm rounded-t-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                        <option>Statistics</option>
                        <option>Services</option>
                        <option>FAQ</option>
                    </select>
                </div>
                <ul class="hidden text-sm font-medium text-center text-gray-500 divide-x divide-gray-200 rounded-lg sm:flex dark:divide-gray-600 dark:text-gray-400" id="fullWidthTab" data-tabs-toggle="#fullWidthTabContent" role="tablist">
                    <li class="w-full">
                        <button id="sessions-tab" data-tabs-target="#sessions" type="button" role="tab" aria-controls="sessions" aria-selected="true" class="inline-block w-full p-4 rounded-tl-lg bg-gray-50 hover:bg-gray-100 focus:outline-none dark:bg-gray-700 dark:hover:bg-gray-600">Current Sessions</button>
                    </li>
                    <li class="w-full">
                        <button id="about-tab" data-tabs-target="#about" type="button" role="tab" aria-controls="about" aria-selected="false" class="inline-block w-full p-4 rounded-tr-lg bg-gray-50 hover:bg-gray-100 focus:outline-none dark:bg-gray-700 dark:hover:bg-gray-600">Recently Added</button>
                    </li>
                </ul>
                <div id="fullWidthTabContent" class="border-t border-gray-200 dark:border-gray-600">
                    <div class="hidden pt-4" id="sessions" role="tabpanel" aria-labelledby="sessions-tab">
                      <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
                          @foreach ($allUsers as $login)
                              @php
                                  $userColor = '#' . substr(md5($login->id), 0, 6);
                              @endphp  
                              <li class="py-3 sm:py-4">
                                  <div class="flex items-center justify-between">
                                  <div class="flex items-center min-w-0">
                                      @if($login->profile_picture == null)
                                      <span class="w-10 h-10 flex justify-center items-center rounded-full text-white font-bold
                                          user-color" style="--user-color: {{ $userColor }};">
                                          {{ strtoupper(substr($login->fname, 0, 1)) }}{{ strtoupper(substr($login->lname, 0, 1)) }}
                                      </span>
                                      @else
                                        <img class="w-8 h-8 rounded-full" src="{{ Storage::url($login->profile_picture) }}"  alt="{{$login->lname}}">
                                      @endif
                                      <div class="ml-3">
                                      <p class="font-medium text-sm text-gray-900 truncate dark:text-white">
                                          {{$login->lname}} {{$login->fname}} {{substr($login->mname,0,1)}}.
                                      </p>
                                      <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                                          {{$login->email}}
                                      </p>
                                      </div>
                                  </div>
                                  <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
                                      {{ \Carbon\Carbon::createFromTimestamp($login->last_activity)->diffForHumans() }}
                                  </div>
                                  </div>
                              </li>
                          @endforeach                         
                      </ul>
                    </div>

                    <div class="hidden pt-4" id="about" role="tabpanel" aria-labelledby="about-tab">
                      <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
                        @foreach ($users as $lastCreatedUsers)
                        @php
                            $userColor = '#' . substr(md5($lastCreatedUsers->id), 0, 6);
                        @endphp  
                        <li class="py-3 sm:py-4">
                            <div class="flex items-center justify-between">
                            <div class="flex items-center min-w-0">
                                @if($lastCreatedUsers->profile_picture == null)
                                <span class="w-10 h-10 flex justify-center items-center rounded-full text-white font-bold 
                                    user-color" style="--user-color: {{ $userColor }};">
                                    {{ strtoupper(substr($lastCreatedUsers->fname, 0, 1)) }}{{ strtoupper(substr($lastCreatedUsers->lname, 0, 1)) }}
                                </span>
                                @else
                                  <img class="w-8 h-8 rounded-full" src="{{ Storage::url($lastCreatedUsers->profile_picture) }}"  alt="{{$lastCreatedUsers->lname}}">
                                @endif
                                <div class="ml-3">
                                <p class="font-medium text-sm text-gray-900 truncate dark:text-white">
                                    {{$lastCreatedUsers->lname}} {{$lastCreatedUsers->fname}} {{substr($lastCreatedUsers->mname,0,1)}}.
                                </p>
                                <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                                    {{$lastCreatedUsers->email}}
                                </p>
                                </div>
                            </div>
                            <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
                                {{ \Carbon\Carbon::parse($lastCreatedUsers->created_at)->format('m/d/Y')}}
                            </div>
                            </div>
                        </li>
                        @endforeach              
                      </ul>
                    </div>
                </div>

                <!-- Card Footer -->
                {{-- <div class="flex items-center justify-between pt-3 mt-5 border-t border-gray-200 sm:pt-6 dark:border-gray-700">
                  <div>
                    <button class="inline-flex items-center p-2 text-sm font-medium text-center text-gray-500 rounded-lg hover:text-gray-900 dark:text-gray-400 dark:hover:text-white" type="button" data-dropdown-toggle="stats-dropdown">Last 7 days <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg></button>
                    <!-- Dropdown menu -->
                    <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded shadow dark:bg-gray-700 dark:divide-gray-600" id="stats-dropdown">
                        <div class="px-4 py-3" role="none">
                          <p class="text-sm font-medium text-gray-900 truncate dark:text-white" role="none">
                            Sep 16, 2021 - Sep 22, 2021
                          </p>
                        </div>
                        <ul class="py-1" role="none">
                          <li>
                            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Yesterday</a>
                          </li>
                          <li>
                            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Today</a>
                          </li>
                          <li>
                            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Last 7 days</a>
                          </li>
                          <li>
                            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Last 30 days</a>
                          </li>
                          <li>
                            <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Last 90 days</a>
                          </li>
                        </ul>
                        <div class="py-1" role="none">
                          <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Custom...</a>
                        </div>
                    </div>
                  </div>
                  <div class="flex-shrink-0">
                    <a href="#" class="inline-flex items-center p-2 text-xs font-medium uppercase rounded-lg text-blue-700 sm:text-sm hover:bg-gray-100 dark:text-blue-500 dark:hover:bg-gray-700">
                      Full Report
                      <svg class="w-4 h-4 ml-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg>
                    </a>
                  </div>
                </div> --}}
              </div>
            @endif
          </div>

          <!--3 widget -->
          {{-- <div class="grid w-full grid-cols-1 gap-4 mt-4 xl:grid-cols-2 2xl:grid-cols-3">
            <div class="items-center justify-between p-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:flex dark:border-gray-700 sm:p-6 dark:bg-gray-800">
              <div class="w-full">
                <h3 class="text-base font-normal text-gray-500 dark:text-gray-400">New tickets</h3>
                <span class="text-2xl font-bold leading-none text-gray-900 sm:text-3xl dark:text-white">2,340</span>
                <p class="flex items-center text-base font-normal text-gray-500 dark:text-gray-400">
                  <span class="flex items-center mr-1.5 text-sm text-green-500 dark:text-green-400">
                    <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                      <path clip-rule="evenodd" fill-rule="evenodd" d="M10 17a.75.75 0 01-.75-.75V5.612L5.29 9.77a.75.75 0 01-1.08-1.04l5.25-5.5a.75.75 0 011.08 0l5.25 5.5a.75.75 0 11-1.08 1.04l-3.96-4.158V16.25A.75.75 0 0110 17z"></path>
                    </svg>
                    12.5% 
                  </span>
                  Since last month
                </p>
              </div>
              <div class="w-full" id="new-products-chart"></div>
            </div>
            <div class="items-center justify-between p-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:flex dark:border-gray-700 sm:p-6 dark:bg-gray-800">
              <div class="w-full">
                <h3 class="text-base font-normal text-gray-500 dark:text-gray-400">Users</h3>
                <span class="text-2xl font-bold leading-none text-gray-900 sm:text-3xl dark:text-white">2,340</span>
                <p class="flex items-center text-base font-normal text-gray-500 dark:text-gray-400">
                  <span class="flex items-center mr-1.5 text-sm text-green-500 dark:text-green-400">
                    <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                      <path clip-rule="evenodd" fill-rule="evenodd" d="M10 17a.75.75 0 01-.75-.75V5.612L5.29 9.77a.75.75 0 01-1.08-1.04l5.25-5.5a.75.75 0 011.08 0l5.25 5.5a.75.75 0 11-1.08 1.04l-3.96-4.158V16.25A.75.75 0 0110 17z"></path>
                    </svg>
                    3,4% 
                  </span>
                  Since last month
                </p>
              </div>
              <div class="w-full" id="week-signups-chart"></div>
            </div>
            <div class="p-4 bg-white border border-gray-200 rounded-lg shadow-sm dark:border-gray-700 sm:p-6 dark:bg-gray-800">
              <div class="w-full">
                <h3 class="mb-2 text-base font-normal text-gray-500 dark:text-gray-400">Audience by age</h3>
                <div class="flex items-center mb-2">
                  <div class="w-16 text-sm font-medium dark:text-white">50+</div>
                  <div class="w-full bg-gray-200 rounded-full h-2.5 dark:bg-gray-700">
                    <div class="bg-blue-600 h-2.5 rounded-full dark:bg-blue-500" style="width: 18%"></div>
                  </div>
                </div>
                <div class="flex items-center mb-2">
                  <div class="w-16 text-sm font-medium dark:text-white">40+</div>
                  <div class="w-full bg-gray-200 rounded-full h-2.5 dark:bg-gray-700">
                    <div class="bg-blue-600 h-2.5 rounded-full dark:bg-blue-500" style="width: 15%"></div>
                  </div>
                </div>
                <div class="flex items-center mb-2">
                  <div class="w-16 text-sm font-medium dark:text-white">30+</div>
                  <div class="w-full bg-gray-200 rounded-full h-2.5 dark:bg-gray-700">
                    <div class="bg-blue-600 h-2.5 rounded-full dark:bg-blue-500" style="width: 60%"></div>
                  </div>
                </div>
                <div class="flex items-center mb-2">
                  <div class="w-16 text-sm font-medium dark:text-white">20+</div>
                  <div class="w-full bg-gray-200 rounded-full h-2.5 dark:bg-gray-700">
                    <div class="bg-blue-600 h-2.5 rounded-full dark:bg-blue-500" style="width: 30%"></div>
                  </div>
                </div>
              </div>
              <div id="traffic-channels-chart" class="w-full"></div>
            </div>
          </div> --}}

          <script src="https://cdn.jsdelivr.net/npm/apexcharts@3.46.0/dist/apexcharts.min.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.js"></script>
    </div>
</section>
<script>
  const getChartOptions = () => {
    // Get counts from the updated elements
    const openTickets = parseInt(document.getElementById('open-tickets').dataset.count) || 0;
    const inProgressTickets = parseInt(document.getElementById('inprogress-tickets').dataset.count) || 0;
    const onHoldTickets = parseInt(document.getElementById('onhold-tickets').dataset.count) || 0;
    const closedTickets = parseInt(document.getElementById('closed-tickets').dataset.count) || 0;
    const cancelledTickets = parseInt(document.getElementById('cancelled-tickets').dataset.count) || 0;

    const TotalTickets = openTickets + inProgressTickets + onHoldTickets + closedTickets + cancelledTickets;

    // Prevent division by zero
    const percentage = (count) => TotalTickets > 0 ? (count / TotalTickets) * 100 : 0;

    return {
      series: [
        percentage(openTickets), 
        percentage(inProgressTickets), 
        percentage(onHoldTickets), 
        percentage(closedTickets), 
        percentage(cancelledTickets)
      ],
      colors: ["#1C64F2", "#FF8A00", "#E2D9F3", "#16BDCA", "#FF6B6B"],
      chart: {
        height: "350px",
        width: "100%",
        type: "radialBar",
        sparkline: {
          enabled: true,
        },
      },
      plotOptions: {
        radialBar: {
          track: {
            background: '#E5E7EB',
          },
          dataLabels: {
            show: false,
          },
          hollow: {
            margin: 0,
            size: "32%",
          }
        },
      },
      grid: {
        show: false,
        strokeDashArray: 4,
        padding: {
          left: 2,
          right: 2,
          top: -23,
          bottom: -20,
        },
      },
      labels: ["Open", "In progress", "On-hold", "Closed", "Cancelled"],
      legend: {
        show: true,
        position: "bottom",
        fontFamily: "Inter, sans-serif",
      },
      tooltip: {
        enabled: true,
        x: {
          show: false,
        },
      },
      yaxis: {
        show: false,
        labels: {
          formatter: function (value) {
            return value + '%';
          }
        }
      }
    }
  };

  let chart;  // Define globally

  if (document.getElementById("radial-chart") && typeof ApexCharts !== 'undefined') {
    chart = new ApexCharts(document.querySelector("#radial-chart"), getChartOptions());
    chart.render();
  }

  document.querySelectorAll('[data-dropdown-toggle="weekly-sales-dropdown"] a').forEach(item => {
  item.addEventListener('click', function(event) {
    event.preventDefault();
    const range = this.textContent.trim(); // Get the selected range

    // Update the button text
    const dropdownButton = document.getElementById('dropdownButton');
    if (dropdownButton) {
      dropdownButton.innerText = range;
    }

    // Fetch and update ticket counts
    updateTickets(range);
  });
});

  function updateTickets(range) {
    fetch(`/get-ticket-counts?range=${range}`)
      .then(response => response.json())
      .then(data => {
        updateTicketCount('open-tickets', data.open);
        updateTicketCount('inprogress-tickets', data.inprogress);
        updateTicketCount('onhold-tickets', data.onhold);
        updateTicketCount('closed-tickets', data.closed);
        updateTicketCount('cancelled-tickets', data.cancelled);

        if (chart) {
          chart.updateOptions(getChartOptions());
        }
      })
      .catch(error => console.error('Error fetching data: ', error));
  }

  function updateTicketCount(elementId, count) {
    const element = document.getElementById(elementId);
    if (element) {
      element.innerText = count ?? 0;  // Update displayed count
      element.setAttribute('data-count', count ?? 0);  // Update data-count attribute
    }
  }
</script>

{{-- <script>     
    const getChartOptions = () => {
      //Get counts
      const openTickets = parseInt(document.getElementById('open-tickets').dataset.count) || 0;
      const inProgressTickets = parseInt(document.getElementById('inprogress-tickets').dataset.count)  || 0;
      const onHoldTickets = parseInt(document.getElementById('onhold-tickets').dataset.count) || 0;
      const closedTickets = parseInt(document.getElementById('closed-tickets').dataset.count) || 0;
      const cancelledTickets = parseInt(document.getElementById('cancelled-tickets').dataset.count) || 0;
    
      const TotalTickets = openTickets + inProgressTickets + onHoldTickets + closedTickets + cancelledTickets;
      
      const percentage = (count) => TotalTickets > 0 ? (count / TotalTickets) * 100 : 0;

      // const openTicketsPercentage = (openTickets / TotalTickets) * 100;
      // const inProgressTicketsPercentage = (inProgressTickets / TotalTickets) * 100;
      // const onHoldTicketsPercentage = (onHoldTickets / TotalTickets) * 100;
      // const closedTicketsPercentage = (closedTickets / TotalTickets) * 100;
      // const cancelledTicketsPercentage = (cancelledTickets / TotalTickets) * 100;
    
      return {
        // series: [openTicketsPercentage, inProgressTicketsPercentage, onHoldTicketsPercentage, closedTicketsPercentage, cancelledTicketsPercentage],
        series: [percentage(openTickets), 
        percentage(inProgressTickets), 
        percentage(onHoldTickets), 
        percentage(closedTickets), 
        percentage(cancelledTickets)
      ],
        colors: ["#1C64F2", "#FF8A00", "#E2D9F3", "#16BDCA", "#FF6B6B"],
        chart: {
          height: "350px",
          width: "100%",
          type: "radialBar",
          sparkline: {
            enabled: true,
          },
        },
        plotOptions: {
          radialBar: {
            track: {
              background: '#E5E7EB',
            },
            dataLabels: {
              show: false,
            },
            hollow: {
              margin: 0,
              size: "32%",
            }
          },
        },
        grid: {
          show: false,
          strokeDashArray: 4,
          padding: {
            left: 2,
            right: 2,
            top: -23,
            bottom: -20,
          },
        },
        labels: ["Open", "In progress", "On-hold", "Closed", "Cancelled"],
        legend: {
          show: true,
          position: "bottom",
          fontFamily: "Inter, sans-serif",
        },
        tooltip: {
          enabled: true,
          x: {
            show: false,
          },
        },
        yaxis: {
          show: false,
          labels: {
            formatter: function (value) {
              return value + '%';
            }
          }
        }
      }
    }

    let chart;

    if (document.getElementById("radial-chart") && typeof ApexCharts !== 'undefined') {
      const chart = new ApexCharts(document.querySelector("#radial-chart"), getChartOptions());
      chart.render();
    }

    document.querySelectorAll('[data-dropdown-toggle="weekly-sales-dropdown"] a').forEach(item => {
      item.addEventListener('click', function(event) {
        event.preventDefault();
        const range = this.textContent.trim(); // Get the selected range
        updateTickets(range);
      });
    });

  function updateTickets(range) {
    fetch(`/get-ticket-counts?range=${range}`)
      .then(response => response.json())
      .then(data => {
        document.getElementById('open-tickets').innerText = data.open;
        document.getElementById('open-tickets').setAttribute('data-count', data.open);

        document.getElementById('inprogress-tickets').innerText = data.inprogress;
        document.getElementById('inprogress-tickets').setAttribute('data-count', data.inprogress);

        document.getElementById('onhold-tickets').innerText = data.onhold;
        document.getElementById('onhold-tickets').setAttribute('data-count', data.onhold);

        document.getElementById('closed-tickets').innerText = data.closed;
        document.getElementById('closed-tickets').setAttribute('data-count', data.closed);

        document.getElementById('cancelled-tickets').innerText = data.cancelled;
        document.getElementById('cancelled-tickets').setAttribute('data-count', data.cancelled);

        chart.updateOptions(getChartOptions());

      })
      .catch(error => console.error('Error fetching data: ', error));
  }
</script> --}}
@else
    <p>Please <a href="{{ route('login') }}">login</a> to access tickets.</p>
@endif
@endsection